apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
  namespace: job-market
data:
  MINIO_BUCKET_BRONZE: bronze
  MINIO_BUCKET_SILVER: silver
  MINIO_BUCKET_GOLD: gold
  MINIO_REGION: us-east-1