apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-secret
  namespace: job-market
type: Opaque
stringData:
  password: mn31pxDw9Wex4s6EqkyexXHQ # kubectl get secret topcv-es-elastic-user -n elastic-stack -o go-template='{{.data.elastic | base64decode}}'
