apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-search-api
  namespace: job-market
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-search-api
  template:
    metadata:
      labels:
        app: job-search-api
    spec:
      containers:
        - name: job-search-api
          image: job-search-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: ELASTICSEARCH_URL
              value: "http://elasticsearch:9200"
            - name: JOBS_INDEX
              value: "gold-jobs-flat"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
