apiVersion: v1
kind: Namespace
metadata:
  name: spark
---
apiVersion: v1
kind: Namespace
metadata:
  name: search
---
apiVersion: v1
kind: Namespace
metadata:
  name: serving
---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka
