apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-speed-checkpoints-pvc
  namespace: spark
  labels:
    app: speed-stream
    component: checkpoint
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
