apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: jobs-raw
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  topicName: jobs_raw
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: jobs-clean
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  topicName: jobs_clean
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: jobs-dead-letter
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  topicName: jobs_dead_letter
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000

